# -*- coding: utf-8 -*-
"""amritsar_pilot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuqGo55BqcTKaHaY95NbHHXM66iIrTBt

# regression for transport expenditure

* import the csv file into the colab environment first
* then using pandas library import it as a dataframe using the file path.
* take help from any LLM as they are very efficient in python coding.
* alternatively for analysis you can also use STATA or R-progamming.
"""

import pandas as pd

df = pd.read_csv('') #copy the file path inside the parantheses.

import statsmodels.formula.api as smf

#running the model
model = smf.ols(
    'monthly_transport_exp ~ treated + did + VI_did + VI '
    '+ C(survey_location) + C(period)',
    data=df
).fit(cov_type='cluster', cov_kwds={'groups': df['survey_location']})

#defining and converting the results into a table
coefs = ['Intercept', 'treated', 'did', 'VI_did', 'VI']
results = pd.DataFrame({
    'coef': model.params[coefs],
    'se':   model.bse[coefs],
    'p':    model.pvalues[coefs]
})
print(results)
print(f"\nN = {int(model.nobs)}, R2 = {model.rsquared:.4f}")

display(results.round(4))

#running the model for Average Treatment effect on treated
model = smf.ols(
    'monthly_transport_exp ~ treated + did '
    '+ C(survey_location) + C(period)',
    data=df
).fit(cov_type='cluster', cov_kwds={'groups': df['survey_location']})

#defining and converting the results into a table
coefs = ['Intercept', 'treated', 'did']
results = pd.DataFrame({
    'coef': model.params[coefs],
    'se':   model.bse[coefs],
    'p':    model.pvalues[coefs]
})
print(results)
print(f"\nN = {int(model.nobs)}, R2 = {model.rsquared:.4f}")